version: "3"
services:
  db:
    image: mysql:latest

    container_name: contmysql

    ports:
        - "3306:3306"

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: integrador2

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: